export interface Product {
  id: string;
  name: string;
  description?: string;
  category: string;
  image: string;
}

export const CATEGORIES = [
  "Luvas de Procedimento",
  "TNT Descartáveis",
  "Máscaras",
  "Descartáveis",
  "Higiene",
  "Limpeza",
  "Sacos de Lixo e Lixeiras",
  "Dispenser",
  "EPIs",
  "Diversos"
];

export const PRODUCTS: Product[] = [
  // Luvas de Procedimento
  { id: "luva-1", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA PRETA C/100 UND - INOVEN", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-2", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA AZUL C/100 UND - INOVEN", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-3", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA AZUL C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-4", category: "Luvas de Procedimento", name: "LUVA DE VINIL C/PÓ C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-2.jpg" },
  { id: "luva-5", category: "Luvas de Procedimento", name: "LUVA DE VINIL S/PÓ C/100 UND - INOVEN", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-2.jpg" },
  { id: "luva-6", category: "Luvas de Procedimento", name: "LUVA DE VINIL S/PÓ C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-2.jpg" },
  { id: "luva-7", category: "Luvas de Procedimento", name: "LUVA DE LÁTEX S/PÓ C/100 UND - INOVEN", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-8", category: "Luvas de Procedimento", name: "LUVA DE LÁTEX C/PÓ C/100 UND - INOVEN", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-9", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA ROSA C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-10", category: "Luvas de Procedimento", name: "LUVA LÁTEX POWDER FREE C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-11", category: "Luvas de Procedimento", name: "LUVA LÁTEX C/PÓ C/100 UND - DESCARPACK", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-12", category: "Luvas de Procedimento", name: "LUVA DE LÁTEX S/PÓ C/100 UND - SUPERMAX", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-13", category: "Luvas de Procedimento", name: "LUVA DE LÁTEX C/PÓ C/100 UND - SUPERMAX", description: "Tamanhos: PP / P / M / G", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-14", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA SONIC C/100 UND - SUPERMAX", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-15", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA AZUL C/100 UND - SUPERMAX", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-16", category: "Luvas de Procedimento", name: "LUVA NITRÍLICA ROSA C/100 UND - SUPERMAX", description: "Tamanhos: PP / P / M / G", image: "https://i.postimg.cc/VNn5yDFx/luva-nitrilica.jpg" },
  { id: "luva-17", category: "Luvas de Procedimento", name: "LUVA CIRÚRGICA ESTÉRIL 1 PAR - SUPERMAX", description: "Tamanhos: 6 / 6.5 / 7 / 7.5 / 8 / 8.5", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "luva-18", category: "Luvas de Procedimento", name: "LUVA PLÁSTICA C/100 UND - DESCARPACK", image: "https://www.glotex.com.br/assets/img/luva-2.jpg" },

  // TNT Descartáveis
  { id: "tnt-1", category: "TNT Descartáveis", name: "AVENTAL DESC. ROSA/ AZUL MODELO BLUSA GR PESADA PCT C/ 10 UND", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-2", category: "TNT Descartáveis", name: "AVENTAL DESC. MODELO BLUSA GR LEVE PCT C/ 10", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-3", category: "TNT Descartáveis", name: "AVENTAL CIRURGICO ESTERILIZADO PCT/ 1 UND", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-4", category: "TNT Descartáveis", name: "TOUCA BRANCA SANFONADA PCT C/ 100 UND", image: "https://www.glotex.com.br/assets/img/touca-1.jpg" },
  { id: "tnt-5", category: "TNT Descartáveis", name: "TOUCA COLORIDA SANFONADA PCT C/ 100 UND", image: "https://www.glotex.com.br/assets/img/touca-1.jpg" },
  { id: "tnt-6", category: "TNT Descartáveis", name: "TOUCA BRANCA SANFONADA AFRO 60X60 PCT C/ 50 UND", image: "https://www.glotex.com.br/assets/img/touca-1.jpg" },
  { id: "tnt-7", category: "TNT Descartáveis", name: "PROPÉ DESCARTÁVEL BRANCO PCT C/ 100 UND", image: "https://www.glotex.com.br/assets/img/pro-pre-1.jpg" },
  { id: "tnt-8", category: "TNT Descartáveis", name: "PROTETOR DE BARBA BRANCO PCT C/ 100 UND", image: "https://www.glotex.com.br/assets/img/pro-pre-1.jpg" },
  { id: "tnt-9", category: "TNT Descartáveis", name: "CALÇA DESCARTÁVEL BRANCO PCT C/ 10 UND", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-10", category: "TNT Descartáveis", name: "LENÇOL DE MACA C/ ELASTICO PCT C/ 10 UNIDADES", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-11", category: "TNT Descartáveis", name: "AVENTAL ESPECIAL DE PROTEÇÃO - TYVEK - PCT 1 UND", image: "https://www.glotex.com.br/assets/img/avental-1.jpg" },
  { id: "tnt-12", category: "TNT Descartáveis", name: "LUVA DE BANHO ASSEPSIA PCT C/ 5 UND", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },

  // Máscaras
  { id: "mask-1", category: "Máscaras", name: "MÁSCARA TRIPLA CAMADA CARTUCHO C/ 50 UND (BRANCA)", image: "https://www.glotex.com.br/assets/img/mascara-1.jpg" },
  { id: "mask-2", category: "Máscaras", name: "MÁSCARA TRIPLA CAMADA CARTUCHO C/ 50 UND (AZUL)", image: "https://www.glotex.com.br/assets/img/mascara-1.jpg" },
  { id: "mask-3", category: "Máscaras", name: "MÁSCARA TRIPLA DESCARTÁVEL ROSA PCT C/ 50 UND -A", image: "https://www.glotex.com.br/assets/img/mascara-1.jpg" },
  { id: "mask-4", category: "Máscaras", name: "MÁSCARA TRIPLA CAMADA PRETO - CARTUCHO C/ 50 UND", image: "https://www.glotex.com.br/assets/img/mascara-1.jpg" },
  { id: "mask-5", category: "Máscaras", name: "MÁSCARA TRIPLA DESCARTÁVEL AZUL PCT C/ 50 UND -A", image: "https://www.glotex.com.br/assets/img/mascara-1.jpg" },
  { id: "mask-6", category: "Máscaras", name: "MÁSCARA TRIPLA DESCARTÁVEL INFANTIL - PCT 25 UND", image: "https://www.glotex.com.br/assets/img/mascara-2.jpg" },
  { id: "mask-7", category: "Máscaras", name: "MÁSCARA DESCARTÁVEL TRIPLA DIVERSAS CORES INFANTIL C/ 25 UND", image: "https://www.glotex.com.br/assets/img/mascara-2.jpg" },

  // Descartáveis
  { id: "desc-1", category: "Descartáveis", name: "COPO 50 ML C/100 UND FONPLAST", image: "https://picsum.photos/seed/cup50ml/400/400" },
  { id: "desc-2", category: "Descartáveis", name: "COPO 180 ML C/100 UND FONPLAST", image: "https://picsum.photos/seed/cup180ml/400/400" },
  { id: "desc-3", category: "Descartáveis", name: "COPO 250 ML C/100 UND FONPLAST", image: "https://picsum.photos/seed/cup250ml/400/400" },
  { id: "desc-4", category: "Descartáveis", name: "COPO 50 ML C/100 UND IBRASDE", image: "https://picsum.photos/seed/cup50ml2/400/400" },
  { id: "desc-5", category: "Descartáveis", name: "COPO 180 ML C/100 UND IBRASDE", image: "https://picsum.photos/seed/cup180ml2/400/400" },
  { id: "desc-6", category: "Descartáveis", name: "COPO 330 ML - PP C/50 UND ORLEPLAST", image: "https://picsum.photos/seed/cup330ml/400/400" },
  { id: "desc-7", category: "Descartáveis", name: "COPO 440 ML - PP C/50 UND ORLEPLAST", image: "https://picsum.photos/seed/cup440ml/400/400" },
  { id: "desc-8", category: "Descartáveis", name: "COPO 550 ML - PP C/50 UND ORLEPLAST", image: "https://picsum.photos/seed/cup550ml/400/400" },
  { id: "desc-9", category: "Descartáveis", name: "COPO 700 ML C/25 UND ORLEPLAST", image: "https://picsum.photos/seed/cup700ml/400/400" },
  { id: "desc-10", category: "Descartáveis", name: "KIT POTE E TAMPA 350 ML - C/25 UND ORLEPLAST", image: "https://picsum.photos/seed/pot350ml/400/400" },
  { id: "desc-11", category: "Descartáveis", name: "KIT POTE E TAMPA 500 ML - C/25 UND ORLEPLAST", image: "https://picsum.photos/seed/pot500ml/400/400" },
  { id: "desc-12", category: "Descartáveis", name: "KIT POTE E TAMPA 500 ML - C/12 CONJUNTOS BELLOCOPO", image: "https://picsum.photos/seed/pot500ml2/400/400" },
  { id: "desc-13", category: "Descartáveis", name: "KIT POTE E TAMPA 750 ML - C/15 CONJUNTOS BELLOCOPO", image: "https://picsum.photos/seed/pot750ml/400/400" },
  { id: "desc-14", category: "Descartáveis", name: "KIT POTE E TAMPA 1000 ML - C/14 CONJUNTOS BELLOCOPO", image: "https://picsum.photos/seed/pot1000ml/400/400" },
  { id: "desc-15", category: "Descartáveis", name: "KIT TAMPA POTE 500 ML - C/10 CONJUNTOS BELLOCOPO", image: "https://picsum.photos/seed/lid500ml/400/400" },
  { id: "desc-16", category: "Descartáveis", name: "PRATO 18 CM BRANCO - C/10 UND FONPLAST", image: "https://picsum.photos/seed/plate18cm/400/400" },
  { id: "desc-17", category: "Descartáveis", name: "PRATO 21CM BRANCO - C/10 UND FONPLAST", image: "https://picsum.photos/seed/plate21cm/400/400" },
  { id: "desc-18", category: "Descartáveis", name: "GUARDANAPO 18X20 C/100 UND BIGPEL", image: "https://picsum.photos/seed/napkin18x20/400/400" },
  { id: "desc-19", category: "Descartáveis", name: "GUARDANAPO 21X22 C/50 UND NOBBY", image: "https://picsum.photos/seed/napkin21x22/400/400" },
  { id: "desc-20", category: "Descartáveis", name: "GUARDANAPO 23X22 C/50 UND MAXIM", image: "https://picsum.photos/seed/napkin23x22/400/400" },
  { id: "desc-21", category: "Descartáveis", name: "SUPORTE DE GUARDANAPO P/ MESA BETTANIN", image: "https://picsum.photos/seed/napkinholder/400/400" },
  { id: "desc-22", category: "Descartáveis", name: "GUARDANAPO TV -14X13 PCT C/ 2.000 FOLHAS BIGPEL", image: "https://picsum.photos/seed/napkinTV/400/400" },
  { id: "desc-23", category: "Descartáveis", name: "GUARDANAPO 30X31 C/50 UND NOBBY", image: "https://picsum.photos/seed/napkin30x31/400/400" },
  { id: "desc-24", category: "Descartáveis", name: "PAPEL TOALHA 2 ROLOS 20,5X19 CADA FOLHALEV", image: "https://picsum.photos/seed/papertowel/400/400" },
  { id: "desc-25", category: "Descartáveis", name: "PAPEL TOALHA BOBINA PCT C/ 6 ROLOS 100% CELULOSE CRISTAL PAPER", image: "https://picsum.photos/seed/papertowelroll/400/400" },
  { id: "desc-26", category: "Descartáveis", name: "TOALHA AMERICANA C/ 500 UND BIGPEL (36cm x 25cm)", image: "https://picsum.photos/seed/placemat/400/400" },

  // Higiene
  { id: "hig-1", category: "Higiene", name: "PAPEL HIGIENICO INTERFOLHADO PCT C/ 300 FOLHAS CRISTAL PAPER", image: "https://picsum.photos/seed/toiletpaper/400/400" },
  { id: "hig-2", category: "Higiene", name: "PAPEL HIGIENICO ROLÃO C/ 8 ROLOS 100% CELULOSE CRISTAL PAPER", image: "https://picsum.photos/seed/toiletpaperroll/400/400" },
  { id: "hig-3", category: "Higiene", name: "PAPEL HIGIENICO ROLÃO C/ 8 ROLOS BRANCO SIMPLES", image: "https://picsum.photos/seed/toiletpaperroll2/400/400" },
  { id: "hig-4", category: "Higiene", name: "PAPEL HIGIÊNICO FOLHA DUPLA PCT C/ 12 ROLOS QUALITE", image: "https://picsum.photos/seed/toiletpaper12/400/400" },
  { id: "hig-5", category: "Higiene", name: "PAPEL HIGIENICO C/ 4 ROLOS - FOLHA DUPLA NESS", image: "https://picsum.photos/seed/toiletpaper4/400/400" },
  { id: "hig-6", category: "Higiene", name: "PAPEL HIGIENICO FOLHA DUPLA PCT C/ 16 ROLOS NESS", image: "https://picsum.photos/seed/toiletpaper16/400/400" },
  { id: "hig-7", category: "Higiene", name: "PAPEL INTERFOLHA FOLHA SIMPLES 1000 FOLHAS - ISAPEL", image: "https://picsum.photos/seed/interfoldpaper/400/400" },
  { id: "hig-8", category: "Higiene", name: "PAPEL INTERFOLHA FOLHA DUPLA 800 FOLHAS CRISTAL PAPER", image: "https://picsum.photos/seed/interfoldpaper2/400/400" },
  { id: "hig-9", category: "Higiene", name: "TOALHA UMIDECIDA NEOLEVE", image: "https://picsum.photos/seed/wetwipes/400/400" },

  // Limpeza
  { id: "limp-1", category: "Limpeza", name: "PANO XADREZ 40X60 SIMPLES", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-2", category: "Limpeza", name: "SACO ALVEJADO 40X60 SIMPLES", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-3", category: "Limpeza", name: "PANO DE PRATO 40X65 SIMPLES", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-4", category: "Limpeza", name: "PANO MICROFIBRA 50X70 COLORIDO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-5", category: "Limpeza", name: "FLANELA LARANJA 28X48", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-6", category: "Limpeza", name: "FLANELA BRANCA 28X48", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-7", category: "Limpeza", name: "TOALHA WIPER 25X240 BRANCO 600 PANOS INOVEN", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-8", category: "Limpeza", name: "PLANO MULTIUSO 28X240 AZUL 600 PANOS INOVEN", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-9", category: "Limpeza", name: "PANO MULTIUSO 28X240 VERDE 600 PANOS INOVEN", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-10", category: "Limpeza", name: "ESPONJA DUPLA FACE MULTIUSO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-11", category: "Limpeza", name: "ESCOVA PLÁSTICA", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-12", category: "Limpeza", name: "LÃ DE AÇO PCT C/ 8 UND LUSTRO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-13", category: "Limpeza", name: "FIBRA ABRASIVA DE LIMPEZA PESADA UND", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-14", category: "Limpeza", name: "FIBRA ABRASIVA DE LIMPEZA ULTRA PESADA UND", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-15", category: "Limpeza", name: "FIBRA ABRASIVA DE LIMPEZA LEVE UND", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-16", category: "Limpeza", name: "LIMPA VIDROS 2 EM 1 BRALIMPIA", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-17", category: "Limpeza", name: "LAVA AZULEJO COM CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-18", category: "Limpeza", name: "MOP UMIDO DE LÃ - DIVERSAS CORES", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-19", category: "Limpeza", name: "VASSOURA DE CANTO C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-20", category: "Limpeza", name: "VASSOURA NOVIÇA C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-21", category: "Limpeza", name: "VASSOURA DE NYLON C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-22", category: "Limpeza", name: "VASSOURÃO ESPECIAL C/ CABO 40CM", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-23", category: "Limpeza", name: "VASSOURA DE PALHA C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-24", category: "Limpeza", name: "VASSOURA PIAÇAVA C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-25", category: "Limpeza", name: "RODO PLÁSTICO COM CABO 30 CM - 40 CM - 60 CM", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-26", category: "Limpeza", name: "PASSA CERA COM CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-27", category: "Limpeza", name: "PA PARA LIXO C/ CABO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-28", category: "Limpeza", name: "ÁGUA SANITÁRIA GALÃO 5 LITROS POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-29", category: "Limpeza", name: "DESINFESTANTE GALÃO 5 LITROS DIVERSAS FRAGRÂNCIAS TRIUM", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-30", category: "Limpeza", name: "SABÃO LIQUIDO OMUS GALÃO 5 LITROS POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-31", category: "Limpeza", name: "AMACIANTE CONFORTO GALÃO DE 5 LITROS POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-32", category: "Limpeza", name: "SABONETE LIQUIDO ERVA DOCE GALÃO 5 LITROS TRIUM", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-33", category: "Limpeza", name: "ÁLCOOL 70% GEL GALÃO 5 LITROS POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-34", category: "Limpeza", name: "ÁLCOOL GEL 500 ML POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-35", category: "Limpeza", name: "SABONETE LIQUIDO 500 ML POTIDERM", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-36", category: "Limpeza", name: "ODORIZADOR 60 ML SANITÁRIO POTICO", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-37", category: "Limpeza", name: "MULTIUSO 500 ML POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-38", category: "Limpeza", name: "ODORIZADOR ULTRAFLESH", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-39", category: "Limpeza", name: "ÁLCOOL ETÍLICO 70% - 1 LITRO TUPI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-40", category: "Limpeza", name: "ÁLCOOL ETÍLICO 46% - 1 LITRO FACILITA", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-41", category: "Limpeza", name: "LIMPA ALUMÍNIO 500 ML POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-42", category: "Limpeza", name: "LIMPA VIDROS FACILITA 500 ML", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-43", category: "Limpeza", name: "REMOVEDOR TRADICIONAL 500 ML POTI", image: "https://www.glotex.com.br/assets/img/pano-perfex-1.jpg" },
  { id: "limp-44", category: "Limpeza", name: "LUVA DE BORRACHA PARA LIMPEZA SANRO STANDARD", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },
  { id: "limp-45", category: "Limpeza", name: "LUVA DE LÁTEX AZUL PARA LIMPEZA CELESTE PREMIUM", image: "https://www.glotex.com.br/assets/img/luva-1.jpg" },

  // Sacos de Lixo e Lixeiras
  { id: "lixo-1", category: "Sacos de Lixo e Lixeiras", name: "SACO DE LIXO SIMPLES PACOTES COM 50 UNIDADES 20, 40, 60, 100 LITROS", image: "https://picsum.photos/seed/trashbag/400/400" },
  { id: "lixo-2", category: "Sacos de Lixo e Lixeiras", name: "LIXEIRAS C/ PEDAL DIVERSOS TAMANHOS DIVERSAS CORES MARCA BRALIMPIA", image: "https://picsum.photos/seed/trashbin/400/400" },
  { id: "lixo-3", category: "Sacos de Lixo e Lixeiras", name: "SACO DE LIXO REFORÇADO PACOTES COM 5KG 20, 40, 60, 100 LITROS", image: "https://picsum.photos/seed/trashbagheavy/400/400" },
  { id: "lixo-4", category: "Sacos de Lixo e Lixeiras", name: "SACO DE LIXO EM ROLO 15, 20, 40, 100", image: "https://picsum.photos/seed/trashbagroll/400/400" },
  { id: "lixo-5", category: "Sacos de Lixo e Lixeiras", name: "SACO DE LIXO COLORIDO REFORÇADO PACOTE C/ 5KG 20, 40, 60, 100, 200 LITROS", image: "https://picsum.photos/seed/trashbagcolor/400/400" },

  // Dispenser
  { id: "disp-1", category: "Dispenser", name: "DISPENSER DE PAPEL HIGIENICO CAI-CAI INTERFOLHADO CELMAC", image: "https://picsum.photos/seed/dispenser1/400/400" },
  { id: "disp-2", category: "Dispenser", name: "DISPENSER DE PAPEL INTERFOLHA - CELMAC", image: "https://picsum.photos/seed/dispenser2/400/400" },
  { id: "disp-3", category: "Dispenser", name: "DISPENSER DE PAPEL HIGIENICO ROLÃO CELMAC", image: "https://picsum.photos/seed/dispenser3/400/400" },
  { id: "disp-4", category: "Dispenser", name: "DISPENSER C/ ALAVANCA DE PAPEL TOALHA BOBINA - NOBRE", image: "https://picsum.photos/seed/dispenser4/400/400" },
  { id: "disp-5", category: "Dispenser", name: "DISPENSER DE SABONETE LIQUIDO - BRANCO - CELMAC", image: "https://picsum.photos/seed/dispenser5/400/400" },
  { id: "disp-6", category: "Dispenser", name: "DISPENSER DE COPO DESCARTÁVEL BRANCO (150ML, 180ML, 200ML)", image: "https://picsum.photos/seed/dispenser6/400/400" },

  // EPIs
  { id: "epi-1", category: "EPIs", name: "LUVA DE PU - PRETA C.A 32.034", image: "https://picsum.photos/seed/epiglove1/400/400" },
  { id: "epi-2", category: "EPIs", name: "LUVA LÁTEX VERDE - DORSO TECIDO - CA. 34.860", image: "https://picsum.photos/seed/epiglove2/400/400" },
  { id: "epi-3", category: "EPIs", name: "LUVA APOLLON AMARELA", image: "https://picsum.photos/seed/epiglove3/400/400" },
  { id: "epi-4", category: "EPIs", name: "LUVA POLI. ALGODÃO PONTINHOS LÁTEX COR BRANCA E PRETO", image: "https://picsum.photos/seed/epiglove4/400/400" },
  { id: "epi-5", category: "EPIs", name: "LUVA DE ALGODÃO REVESTIDO C/ LÁTEX", image: "https://picsum.photos/seed/epiglove5/400/400" },
  { id: "epi-6", category: "EPIs", name: "LUVA NITRILO VERDE 33 CM", image: "https://picsum.photos/seed/epiglove6/400/400" },
  { id: "epi-7", category: "EPIs", name: "LUVA DE PROTEÇÃO ANTICORTE C.A 37.266", image: "https://picsum.photos/seed/epiglove7/400/400" },
  { id: "epi-8", category: "EPIs", name: "LUVA NEOPRENE DE BORRACHA C.A 16.779", image: "https://picsum.photos/seed/epiglove8/400/400" },
  { id: "epi-9", category: "EPIs", name: "LUVA DE RASPA 20 CM - C.A 26.749", image: "https://picsum.photos/seed/epiglove9/400/400" },
  { id: "epi-10", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO SUMMER FUME - DELTA PLUS", image: "https://picsum.photos/seed/episafetyglasses1/400/400" },
  { id: "epi-11", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO SUMMER INCOLOR - DELTAPLUS", image: "https://picsum.photos/seed/episafetyglasses2/400/400" },
  { id: "epi-12", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO DE SOBREPOR HEKLA2 DELTAPLUS", image: "https://picsum.photos/seed/episafetyglasses3/400/400" },
  { id: "epi-13", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO SKY FUME - DELTAPLUS", image: "https://picsum.photos/seed/episafetyglasses4/400/400" },
  { id: "epi-14", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO SKY INCOLOR - DELTAPLUS", image: "https://picsum.photos/seed/episafetyglasses5/400/400" },
  { id: "epi-15", category: "EPIs", name: "ÓCULOS DE PROTEÇÃO GALERAS - INCOLOR DELTAPLUS", image: "https://picsum.photos/seed/episafetyglasses6/400/400" },
  { id: "epi-16", category: "EPIs", name: "ABAFADOR TIPO CONCHA CONFORT PLUS 26 DB CA.48054", image: "https://picsum.photos/seed/epiearmuff/400/400" },
  { id: "epi-17", category: "EPIs", name: "PROTETOR AUDITIVO C/CORDÃO DE ALGODÃO - CA. 17.664", image: "https://picsum.photos/seed/epiearplug/400/400" },
  { id: "epi-18", category: "EPIs", name: "COLETE C/ FAIXA REFLETIVA - AMARELO E LARANJA", image: "https://picsum.photos/seed/epivest/400/400" },
  { id: "epi-19", category: "EPIs", name: "CINTURÃO PARAQUEDISTA HAR11", image: "https://picsum.photos/seed/epiharness/400/400" },
  { id: "epi-20", category: "EPIs", name: "KIT 5 PEÇAS - MOSQUETÃO EMAÇO OVAL TRAVA DE ROSCA", image: "https://picsum.photos/seed/epicarabiner/400/400" },
  { id: "epi-21", category: "EPIs", name: "TALABARTE Y PLANO 55 MM", image: "https://picsum.photos/seed/epilanyard/400/400" },
  { id: "epi-22", category: "EPIs", name: "CAPACETE DE PROTEÇÃO DELTAPLUS", image: "https://picsum.photos/seed/epihelmet/400/400" },
  { id: "epi-23", category: "EPIs", name: "CARNEIRA PARA FIXAÇÃO DO CAPACETE - DELTAPLUS", image: "https://picsum.photos/seed/epihelmetpart/400/400" },
  { id: "epi-24", category: "EPIs", name: "JUGULAR DE LONA PARA CAPACETE DE SEGURANÇA", image: "https://picsum.photos/seed/epihelmetstrap/400/400" },
  { id: "epi-25", category: "EPIs", name: "CAPA DE CHUVA DE PVC AMARELA", image: "https://picsum.photos/seed/epiraincoat/400/400" },
  { id: "epi-26", category: "EPIs", name: "CONJUNTO MOTOBOY DELTA PLUS - P AO GG", image: "https://picsum.photos/seed/epimotoboy/400/400" },
  { id: "epi-27", category: "EPIs", name: "CORRENTE DE SINALIZAÇÃO PLÁSTICA ELO - PRETA E AMARELA POR METRO", image: "https://picsum.photos/seed/epichain/400/400" },
  { id: "epi-28", category: "EPIs", name: "CINTA ERGON LYCRA DUPLOELASTICO - PRETO", image: "https://picsum.photos/seed/epibelt/400/400" },
  { id: "epi-29", category: "EPIs", name: "FITA ZEBRADA ROLO - PRETA/AMARELO - 65 MM DELTA PLUS", image: "https://picsum.photos/seed/epitape/400/400" },
  { id: "epi-30", category: "EPIs", name: "MÁSCARA RESPIRATÓRIA PPFF2 COM VÁLVULA PRO AGRO", image: "https://picsum.photos/seed/epimask/400/400" },
  { id: "epi-31", category: "EPIs", name: "BOTA LONDRINHA NOBUCK C/ BICO DE PVC - COR MARROM E PRETO", image: "https://picsum.photos/seed/epiboot1/400/400" },
  { id: "epi-32", category: "EPIs", name: "BOTA SAMPA PRETO BIQ. DE PVC - DELTAPLUS", image: "https://picsum.photos/seed/epiboot2/400/400" },
  { id: "epi-33", category: "EPIs", name: "BOTA SANTOS PRETO BIQ. DE COMPOSITE DELTAPLUS", image: "https://picsum.photos/seed/epiboot3/400/400" },
  { id: "epi-34", category: "EPIs", name: "SAPATO SINOP PRETO BIQ. DE PVC DELTAPLUS", image: "https://picsum.photos/seed/epishoe1/400/400" },
  { id: "epi-35", category: "EPIs", name: "SAPATO ANTIDERRAPANTE BRANCO/ PRETO SOFT WORKS", image: "https://picsum.photos/seed/epishoe2/400/400" },
  { id: "epi-36", category: "EPIs", name: "BOTA DE PVC - C/MEDIO - MEMBRANA FINA BRACOL", image: "https://picsum.photos/seed/epiboot4/400/400" },
  { id: "epi-37", category: "EPIs", name: "CREME PROTETOR DE PELE - LUVA QUIMICA GR 3 PLUS FR - 200 G - NUTRIEX", image: "https://picsum.photos/seed/episkincream/400/400" },
  { id: "epi-38", category: "EPIs", name: "ULTRA HIDRATAÇÃO - REGEDERME G3 - 200 G - NUTRIEX", image: "https://picsum.photos/seed/episkincream2/400/400" },
  { id: "epi-39", category: "EPIs", name: "PROTETOR SOLAR FATOR 30, 60, 70 120ML OU 1L NUTRIEX", image: "https://picsum.photos/seed/sunscreen/400/400" },
  { id: "epi-40", category: "EPIs", name: "BLUSÃO DE RASPA P/ SOLDADOR CA.13991", image: "https://picsum.photos/seed/epiwelding/400/400" },
  { id: "epi-41", category: "EPIs", name: "AVENTAL DE RASPA CA. 25.977", image: "https://picsum.photos/seed/epiapron/400/400" },
  { id: "epi-42", category: "EPIs", name: "LUVA RASPA PUNHO 30CM - CA.16.074", image: "https://picsum.photos/seed/epiglovewelding/400/400" },

  // Diversos
  { id: "div-1", category: "Diversos", name: "CAFÉ TRADICIONAL - 500 GR - BRASILEIRO", image: "https://picsum.photos/seed/coffee/400/400" },
  { id: "div-2", category: "Diversos", name: "CAFÉ EXTRA FORTE PILÃO - 500 GR", image: "https://picsum.photos/seed/coffee2/400/400" },
  { id: "div-3", category: "Diversos", name: "AÇÚCAR REFINADO - 1KG - UNIÃO", image: "https://picsum.photos/seed/sugar/400/400" },
  { id: "div-4", category: "Diversos", name: "ERVA DOCE /CAMOMILA/ HORTELÃ CHÁ LEÃO", image: "https://picsum.photos/seed/tea/400/400" },
  { id: "div-5", category: "Diversos", name: "ADOÇANTE LIQUIDO - 100ML - ZERO CAL", image: "https://picsum.photos/seed/sweetener/400/400" },
  { id: "div-6", category: "Diversos", name: "FILTRO DE CAFÉ 102 MELITTA", image: "https://picsum.photos/seed/coffeefilter/400/400" },
  { id: "div-7", category: "Diversos", name: "CAIXA PERFURO CORTANTE", image: "https://www.glotex.com.br/assets/img/caixa-perfuro-cortante-1.jpg" },
];

export const CONTACT_INFO = {
  phones: ["(11) 97266-2170", "(11) 99310-7658"],
  email: "contato@glotexsolutions.com.br",
  address: "Estrada da Lagoa, 729 – Sl 18 - Lagoa. Vargem Grande Paulista – SP."
};
